language: perl
perl:
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y csh xorg-dev openbox lesstif2-dev libdb-dev libdb++-dev ncbi-blast+
  - ./build/ci/run_build.sh 2>&1 > /dev/null

script: ./build/ci/run_tests.sh

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
#    - master
    - topic/lower_version_req