language: perl
perl:
#  - "5.18"
#  - "5.16"
#  - "5.14"
  - "5.12"

before_install: ./build/ci/run_build.sh

script: "export PATH=$PATH:/home/travis/mgblast:/home/travis/mgblast/ncbi/bin; echo $PATH; which mgblast; which formatdb; which blastn; which makeblastdb;"

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master