language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y csh xorg-dev openbox ncbi-blast+
  - ./build/ci/run_build.sh 2>&1 > /dev/null

script: ./build/ci/run_tests.sh

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master
