language: perl
perl:
#  - "5.18"
#  - "5.16"
#  - "5.14"
  - "5.12"

before_install: ./build/ci/run_build.sh

#script: "export PATH=$PATH:/home/travis/build/sestaton/Transposome/mgblast:/home/travis/build/sestaton/Transposome/mgblast/ncbi/bin; which mgblast; which formatdb; which blastn; which makeblastdb"

script: "perl Makefile.PL && make test"

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master