blast_input:
  - sequence_file:      t_reads.fas
  - sequence_num:       10
  - cpu:                1
  - thread:             1
  - output_directory:   transposome_results_out
clustering_options:
  - in_memory:          1
  - percent_identity:   90
  - fraction_coverage:  0.55
  - merge_threshold:    2
annotation_input:
  - repeat_database:    repeats.fas
annotation_options:
  - cluster_size:       1
  - blast_evalue:       10
output:
  - run_log_file:       t_log.txt
  - cluster_log_file:   t_cluster_report.txt
