blast_input:
  - sequence_file:      t_reads.fas
  - description_num:    100
  - alignment_num:      100
  - sequence_num:       10
  - cpu:                1
  - thread:             1
  - output_directory:   transposome_results_out
clustering_input:
  - blast_file:        transposome_mgblast_iS2b.bln
  - in_memory:         1
clustering_options:
  - percent_identity:  90
  - fraction_coverage: 0.55
  - merge_threshold:   2
annotation_input:
  - repeat_database:  t_bldb
  - repeat_json_file: t_repeats.json
annotation_options:
  - cluster_size:     1
  - blast_evalue:     10
output:
  - report_file:      t_rep.out
